server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bands
    username: szabo-peter
    password: 123456
    initialization-mode: never # always ha használni akarjuk a data.sql-t
    platform: mysql
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create # create, create-drop, update, validate, none
